#!/bin/dash

set -e

echo ">>> Syncing MELPA Stable <$( date +"%Y-%m-%d %H:%M:%S %Z" )>..."

rsync -avz --delete --exclude="- /index.html" --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r rsync://melpa.org/packages-stable/ /var/elpa-packages/melpa-stable

echo ">>> Done <$( date +"%Y-%m-%d %H:%M:%S %Z" )>"
